### ISSUE TITLE
关于编译问题

### ISSUE THREAD

**Issue by crowforkotlin** [equationl/life-game-compose#2]
作者您好，这个是 静态加载的方式，请问有可能实现动态加载这些so产物、klib的方式吗

**Comment by equationl** [comment]
你好，理论上是可以的。

安卓和桌面端都是使用 JVM 实现，可以使用 `System.load()` 加载。

但是安卓端在高版本上对加载外部 SO 做了限制，且如果外部加载 SO 会被应用市场拒绝所以后续没有试过是否依旧可行，你可以自己试试。

而桌面端则没有这些限制。

iOS 端使用的是 cinterop 实现，动态加载我没有研究过，你可以试试

**Comment by crowforkotlin** [comment]
好的，谢谢解答
